secrets:
  transmission_user:
    file: ${PWD}/secrets/transmission_user
  transmission_pass:
    file: ${PWD}/secrets/transmission_pass

services:
  transmission:
    image: lscr.io/linuxserver/transmission:latest
    container_name: transmission
    restart: unless-stopped
    volumes:
      - ${PWD}/tmp/config:/config
      - ${PWD}/tmp/downloads:/downloads
    secrets:
      - transmission_user
      - transmission_pass
    environment:
      PUID: ${PUID}
      PGID: ${PGID}
      TZ: ${TZ}
      FILE__USER: /run/secrets/transmission_user
      FILE__PASS: /run/secrets/transmission_pass
